import React, { useEffect } from 'react';
import { PublicLayout } from './PublicLayout';
import { motion } from 'framer-motion';

const Reveal = ({ children, delay = 0 }: { children: React.ReactNode; delay?: number }) => (
  <motion.div
    initial={{ opacity: 0, y: 10 }}
    whileInView={{ opacity: 1, y: 0 }}
    viewport={{ once: true }}
    transition={{ duration: 0.4, delay: delay / 1000 }}
  >
    {children}
  </motion.div>
);

const sections = [
  {
    title: 'Acceptance of terms',
    items: [
      { term: 'Agreement', detail: 'By using StratifyPM, you agree to these terms. If you do not agree, please discontinue use immediately.' },
      { term: 'Eligibility', detail: 'You must be at least 13 years old to use StratifyPM. By creating an account, you confirm you meet this requirement.' },
      { term: 'Updates', detail: 'We may update these terms over time. Continued use of the platform after updates constitutes acceptance of the revised terms.' },
    ],
  },
  {
    title: 'Acceptable use',
    items: [
      { term: 'Account security', detail: 'You are responsible for maintaining the security of your account. Unauthorized access should be reported immediately.' },
      { term: 'Permitted use', detail: 'StratifyPM is designed for product management work — strategy, analysis, research, prioritization, and planning. Personal and professional use are both welcome.' },
      { term: 'Prohibited actions', detail: 'You may not use StratifyPM to generate harmful content, attempt to reverse-engineer our systems, or deliberately abuse API rate limits.' },
      { term: 'Uploaded data', detail: 'You are responsible for the data you upload. Do not upload highly sensitive personal information such as SSNs or medical records unless necessary for your analysis.' },
    ],
  },
  {
    title: 'AI output liability',
    items: [
      { term: 'Output accuracy', detail: 'Outputs are generated by Claude or Gemini AI models. AI can make mistakes. StratifyPM does not guarantee the accuracy or completeness of any AI-generated content.' },
      { term: 'Your responsibility', detail: 'Always review and validate AI outputs before using them in real business decisions. You are responsible for how you act on AI-generated suggestions.' },
      { term: 'Web search results', detail: 'Live search results via Exa AI reflect public web data. We do not verify or endorse the accuracy of third-party information.' },
    ],
  },
  {
    title: 'Intellectual property',
    items: [
      { term: 'Your content', detail: 'You own your prompts, uploaded data, and the outputs generated during your sessions. We make no claim to your intellectual property.' },
      { term: 'Our platform', detail: "StratifyPM's codebase, interface, and system architecture are our intellectual property. Unauthorized reproduction or distribution is not permitted." },
      { term: 'Feedback', detail: 'If you share feedback or suggestions, we may incorporate them into the product. We appreciate all feedback but cannot offer compensation for it.' },
    ],
  },
  {
    title: 'Disclaimers & liability',
    items: [
      { term: 'As-is service', detail: 'StratifyPM is provided "as is" without warranties of any kind. We do not guarantee uninterrupted or error-free service.' },
      { term: 'Limitation of liability', detail: 'StratifyPM is not liable for any indirect, incidental, or consequential damages arising from your use of the platform or reliance on AI-generated content.' },
      { term: 'Uptime', detail: 'We aim for high availability but cannot guarantee 100% uptime. Scheduled maintenance and unexpected outages may occur.' },
    ],
  },
  {
    title: 'Account termination',
    items: [
      { term: 'Self-termination', detail: 'You may delete your account and all associated data at any time. Account deletion is immediate and permanent.' },
      { term: 'Platform termination', detail: 'We reserve the right to suspend or terminate accounts that violate these terms, with or without prior notice.' },
      { term: 'Effect of termination', detail: 'Upon termination, your access to the platform ends and your data is deleted in accordance with our Privacy Policy.' },
    ],
  },
];

export const TermsPage: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <PublicLayout>
      {/* Header */}
      <section className="bg-zinc-50 dark:bg-zinc-950 pt-20 pb-0 border-b-2 border-zinc-900 dark:border-zinc-100">
        <div className="max-w-7xl mx-auto px-6 pb-16">
          <Reveal>
            <div className="inline-block border-2 border-zinc-900 dark:border-zinc-100 bg-zinc-900 dark:bg-zinc-100 text-zinc-50 dark:text-zinc-900 px-4 py-1 font-mono font-bold uppercase tracking-widest text-xs mb-8">
              [ COMPLIANCE / TERMS ]
            </div>
            <h1 className="text-5xl md:text-7xl font-extrabold font-heading text-zinc-900 dark:text-zinc-50 uppercase tracking-tighter leading-[0.92] mb-6">
              Terms of<br />Service.
            </h1>
            <p className="text-base md:text-lg text-zinc-600 dark:text-zinc-400 max-w-2xl leading-relaxed font-sans">
              Clear, plain-language terms. We believe good terms should be readable, not buried in legal jargon. Here is what you agree to when using StratifyPM.
            </p>
          </Reveal>
        </div>
      </section>

      {/* Content */}
      <section className="bg-zinc-50 dark:bg-zinc-950 py-16 pb-32">
        <div className="max-w-7xl mx-auto px-6">
          <Reveal delay={100}>
            <div className="grid md:grid-cols-4 gap-8 mb-12 pb-12 border-b-2 border-zinc-200 dark:border-zinc-800">
              <div className="md:col-span-1">
                <p className="font-mono text-sm leading-relaxed text-zinc-500 dark:text-zinc-500">
                  Document ID<br />
                  <span className="text-zinc-900 dark:text-zinc-100 font-bold">TRM-SYS-01</span>
                </p>
                <p className="font-mono text-sm leading-relaxed text-zinc-500 dark:text-zinc-500 mt-6">
                  Last Updated<br />
                  <span className="text-zinc-900 dark:text-zinc-100 font-bold uppercase">May {new Date().getFullYear()}</span>
                </p>
              </div>
              <div className="md:col-span-3">
                <p className="text-xl md:text-2xl font-sans text-zinc-900 dark:text-zinc-100 leading-snug">
                  These terms govern your use of StratifyPM. We have written them to be clear and fair. If something seems unclear, reach out — we are happy to explain.
                </p>
              </div>
            </div>
          </Reveal>

          <div className="border-2 border-zinc-900 dark:border-zinc-100">
            {sections.map((section, si) => (
              <div key={section.title} className="border-b-2 border-zinc-900 dark:border-zinc-100 last:border-b-0">
                <Reveal delay={si * 50}>
                  <div className="grid md:grid-cols-4 min-h-full">
                    {/* Section label */}
                    <div className="md:col-span-1 bg-zinc-100 dark:bg-zinc-900 p-8 border-b-2 md:border-b-0 md:border-r-2 border-zinc-900 dark:border-zinc-100">
                      <h2 className="text-base font-bold font-heading uppercase text-zinc-900 dark:text-zinc-50 tracking-wide leading-tight">
                        {section.title}
                      </h2>
                      <div className="mt-6 font-mono text-[10px] text-zinc-400 dark:text-zinc-500 uppercase tracking-wider">
                        SECT_{String(si + 1).padStart(2, '0')}
                      </div>
                    </div>

                    {/* Items */}
                    <div className="md:col-span-3 divide-y-2 divide-zinc-200 dark:divide-zinc-800">
                      {section.items.map((item) => (
                        <div key={item.term} className="p-8 grid md:grid-cols-3 gap-6 hover:bg-zinc-100 dark:hover:bg-zinc-900 transition-colors">
                          <div className="md:col-span-1 font-mono text-sm font-bold text-zinc-900 dark:text-zinc-100">
                            → {item.term}
                          </div>
                          <div className="md:col-span-2 text-sm font-sans leading-relaxed text-zinc-600 dark:text-zinc-400">
                            {item.detail}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </Reveal>
              </div>
            ))}
          </div>

          {/* Contact block */}
          <Reveal delay={200}>
            <div className="mt-16 border-2 border-zinc-900 dark:border-zinc-100 p-10 md:p-12 bg-zinc-900 dark:bg-zinc-100 shadow-[8px_8px_0_0_#CCFF00] dark:shadow-[8px_8px_0_0_#18181b]">
              <h2 className="text-xl md:text-2xl font-bold font-heading uppercase text-zinc-50 dark:text-zinc-900 mb-3">
                Questions about these terms?
              </h2>
              <p className="font-sans text-sm text-zinc-400 dark:text-zinc-600 leading-relaxed max-w-2xl mb-8">
                If any of these terms are unclear or you have a specific question, reach out directly. We are happy to clarify.
              </p>
              <a
                href="mailto:bijarniya.m@northeastern.edu"
                className="inline-block bg-chartreuse text-zinc-900 font-bold uppercase tracking-widest text-sm px-8 py-3.5 border-2 border-zinc-50 dark:border-zinc-900 hover:bg-zinc-50 dark:hover:bg-zinc-900 hover:text-zinc-900 dark:hover:text-chartreuse transition-all shadow-[4px_4px_0_0_rgba(0,0,0,0.3)]"
              >
                Get in Touch →
              </a>
            </div>
          </Reveal>
        </div>
      </section>
    </PublicLayout>
  );
};

export default TermsPage;
