import React, { useRef, useEffect } from 'react';
import { PublicLayout } from './PublicLayout';
import { motion, useInView } from 'framer-motion';

// ─── Animation ───────────────────────────────────────────────────────

const Reveal: React.FC<{
  children: React.ReactNode;
  delay?: number;
  className?: string;
}> = ({ children, delay = 0, className }) => {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: '-40px' });
  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 28 }}
      animate={inView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.55, delay, ease: [0.22, 1, 0.36, 1] }}
      className={className}
    >
      {children}
    </motion.div>
  );
};

// ─── Data ────────────────────────────────────────────────────────────

const border = 'border-slate-200 dark:border-slate-800';
const borderB = `border-b ${border}`;

const sections = [
  {
    title: 'Acceptance of terms',
    items: [
      { term: 'Agreement', detail: 'By accessing or using StratifyPM, you agree to be bound by these Terms of Service. If you do not agree, do not use the service.' },
      { term: 'Eligibility', detail: 'You must be at least 13 years old to use StratifyPM. By using the service, you represent that you meet this requirement.' },
      { term: 'Changes', detail: 'We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.' },
    ],
  },
  {
    title: 'Use of the service',
    items: [
      { term: 'Account', detail: 'You are responsible for maintaining the confidentiality of your account. Notify us immediately of any unauthorized access.' },
      { term: 'Permitted use', detail: 'StratifyPM is intended for product management, strategic planning, and data analysis. You may use it for personal or professional purposes.' },
      { term: 'Prohibited use', detail: 'You may not use the service to generate harmful, illegal, or misleading content, attempt to reverse-engineer the platform, or abuse API rate limits.' },
      { term: 'File uploads', detail: 'You are solely responsible for the content you upload. Do not upload files containing sensitive personal data (SSN, medical records, etc.) unless necessary for your analysis.' },
    ],
  },
  {
    title: 'AI-generated content',
    items: [
      { term: 'No guarantee', detail: 'AI responses are generated by third-party models (Claude, Gemini) and may contain inaccuracies. StratifyPM does not guarantee the correctness, completeness, or reliability of AI outputs.' },
      { term: 'Your responsibility', detail: 'You are responsible for reviewing and validating AI-generated content before making business decisions based on it.' },
      { term: 'Web search data', detail: 'Real-time search results are provided by Exa AI and reflect publicly available information. We do not verify the accuracy of third-party sources.' },
    ],
  },
  {
    title: 'Intellectual property',
    items: [
      { term: 'Your content', detail: 'You retain ownership of all content you create or upload. We do not claim any rights to your conversations, files, or analyses.' },
      { term: 'Our platform', detail: 'StratifyPM, its design, code, and branding are the intellectual property of StratifyPM. You may not copy, modify, or distribute the platform without permission.' },
      { term: 'Feedback', detail: 'If you provide feedback or suggestions, we may use them to improve the service without obligation to you.' },
    ],
  },
  {
    title: 'Limitation of liability',
    items: [
      { term: 'As-is service', detail: 'StratifyPM is provided "as is" without warranties of any kind, express or implied, including fitness for a particular purpose.' },
      { term: 'No liability for AI', detail: 'We are not liable for any decisions made based on AI-generated content or for any losses resulting from inaccurate AI outputs.' },
      { term: 'Service availability', detail: 'We do not guarantee uninterrupted access. The service may be temporarily unavailable due to maintenance, updates, or factors beyond our control.' },
    ],
  },
  {
    title: 'Termination',
    items: [
      { term: 'By you', detail: 'You may stop using the service at any time. Contact us to request full account and data deletion.' },
      { term: 'By us', detail: 'We reserve the right to suspend or terminate accounts that violate these terms or engage in abusive behavior.' },
      { term: 'Effect', detail: 'Upon termination, your right to access the service ceases. We may delete your data in accordance with our Privacy Policy.' },
    ],
  },
];

// ─── Component ───────────────────────────────────────────────────────

export const TermsPage: React.FC = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <PublicLayout>
      {/* ━━ Hero ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <section className={borderB}>
        <div className="mx-auto w-full max-w-7xl px-6 py-20 lg:py-28">
          <Reveal>
            <div className="mx-auto max-w-3xl">
              <p className="mb-4 text-xs font-semibold uppercase tracking-[0.2em] text-slate-500 dark:text-slate-400">
                Terms of Service
              </p>
              <h1 className="text-4xl font-bold leading-[1.1] tracking-tight text-slate-900 dark:text-white sm:text-5xl">
                Simple terms, no surprises
              </h1>
              <p className="mt-6 text-lg leading-relaxed text-slate-600 dark:text-slate-400">
                These terms govern your use of StratifyPM. We've kept them straightforward — no legal jargon walls. If anything is unclear, reach out.
              </p>
              <p className="mt-4 text-sm text-slate-400 dark:text-slate-500">
                Last updated: March {new Date().getFullYear()}
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      {/* ━━ Sections ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      {sections.map((section, si) => (
        <section key={section.title} className={si < sections.length - 1 ? borderB : ''}>
          <div className="mx-auto w-full max-w-7xl px-6 py-16 lg:py-20">
            <Reveal>
              <h2 className="mb-10 text-2xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-3xl">
                {section.title}
              </h2>
            </Reveal>

            <Reveal delay={0.05}>
              <div className={`overflow-hidden rounded-lg border ${border}`}>
                {section.items.map((item, i) => (
                  <div
                    key={item.term}
                    className={[
                      'grid gap-2 p-6 sm:grid-cols-3 sm:gap-8 sm:p-8',
                      i < section.items.length - 1 ? borderB : '',
                    ].join(' ')}
                  >
                    <div className="text-sm font-semibold text-slate-900 dark:text-white">
                      {item.term}
                    </div>
                    <div className="text-sm leading-relaxed text-slate-500 dark:text-slate-400 sm:col-span-2">
                      {item.detail}
                    </div>
                  </div>
                ))}
              </div>
            </Reveal>
          </div>
        </section>
      ))}

      {/* ━━ Contact ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      <section>
        <div className="mx-auto w-full max-w-7xl px-6 py-16 lg:py-20">
          <Reveal>
            <div className={`rounded-lg border ${border} p-8 sm:p-12`}>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                Questions about these terms?
              </h2>
              <p className="mt-3 max-w-lg text-sm leading-relaxed text-slate-500 dark:text-slate-400">
                If anything here is unclear or you have concerns, contact us at{' '}
                <a
                  href="mailto:bijarniya.m@northeastern.edu"
                  className="font-medium text-slate-900 underline decoration-slate-300 underline-offset-2 transition hover:decoration-slate-900 dark:text-white dark:decoration-slate-600 dark:hover:decoration-white"
                >
                  bijarniya.m@northeastern.edu
                </a>
              </p>
            </div>
          </Reveal>
        </div>
      </section>
    </PublicLayout>
  );
};
